FROM node:12

#App directory
WORKDIR /usr/src/app

#Install app dependencies
COPY package*.json

RUN npm install

#Bundle app source
COPY . .

#Expose port 8080 
EXPOSE 8080

#Start server
CMD [ "node" , "server.js"]